name: eshop
services:
  catalog.db:
    image: postgres:17-alpine
    container_name: catalog_db
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: catalogs
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/volumes/postgres/EShop:/var/lib/postgresql/data
    

volumes:
  postgres_catalog:
#  catalog.api:
#    image: catalog.api
#    environment:
#        - ASPNETCORE_ENVIRONMENT=Development
#        - ASPNETCORE_HTTP_PORT=5000
#        - ASPNETCORE_HTTPS_PORT=5001
#    ports:
#      - "5000:5000"
#      - "5001:5001"
#    build:
#      context: .
#      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
